# Numpy Arrays

În momentul în care dorim să procesăm anumite imagini folosind Python, aceste imagini o să fie cicite ca și formă de array. Din acest motiv o să începem cu anumite opreații care cu arrays pentru a ne obișnui cu acest set de date.

In [2]:
import numpy as np

Putem să creem ușor un array folosind librăria NumPy. Atunci când o să citim o imagine, acel array o să ne fie creat automat, dar există și opțiunea de a crea de la 0 un array. O să începem prin a crea un array dintr-o listă din Python.

In [3]:
my_list = [1, 2, 3]

Pentru a crea un array dintr-o listă trebuie să îi pasă acea listă ca și argument la np.array()

In [4]:
np.array(my_list)

array([1, 2, 3])

Ceea ce este interesant la acest tip de date (numpy.ndarray) este faptul că acestea pot să existe și în mai multe dimensiuni. Pentru a ne crea un array în mai multe dimensiuni o să ne folosim de metoda np.zeros(). Această metodă ne creează un array de valori 0 și trebuie să îi oferim ca și input shape-ul pe care dorim să îl aibă acest array. Această valoare se va oferi ca și o tuplă. Dacă dorim să creem un array care să aibă 5 rânduri și 3 coloane, atunci o să îi oferim ca și argument valoarea shape=(5, 3)

In [6]:
np.zeros(shape=(5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Numpy are și posibilitatea de a crea un array cu valori random cuprinse între anumite valori. Metoda respectivă poartă denumirea de np.random.randint(). Ca și argumente ia trei valori, prima reprezintă valoarea de la care să înceapă, a doua reprezintă valoarea la care să se oprească, iar cea de a treia reprezintă numărul de valori pe care să îl returneze la întâmplare. Algoritmul de generare de numere random ne permite și să setăm un seed prin comanda np.random.seed(), dar trebuie să fie rulate în același cell pentru a funcționa.

In [11]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [12]:
arr2 = np.random.randint(0, 100, 10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

În cadrul acestor arrays putem să realizăm anumite operații aritmetice prin care să extragem valoarea cea mai mare sau cea mai mică din acest array sau index-ul pe care se găsește acea valoare. De asemenea se pot realiza și operații prin care să îmi aggregeze suma tututor valorilor sau să îmi ne returneze valoarea medie a acestui array.

In [14]:
print(arr.max())  # valoarea cea mai mare
print(arr.argmax())  # index-ul pe care se găsește valoarea cea mai mare

print(arr.min())  # valoarea cea mai mică
print(arr.argmin())  # index-ul pe care se găsește valoarea cea mai mică

print(arr.sum())  # suma tuturor valorilor din array
print(arr.mean())  # media tuturor valorilor din array 

95
0
9
7
608
60.8


Un alt aspect important al acestor arrays este faptul că putem să facem un reshape la acest array. De exemplu, variabila 'arr' este un array care conține 10 elemente pe un singur rând, iar acest array putem să îl schimbăm (să îi facem reshape) la un array care are 10 elemente, dar sunt distribuite altfel, pe 2 rânduri și 5 coloane. Atributul 'shape' de la un numpy.ndarray ne retunrează ce shape are acel array. După ce îi face reshape (utilizând metoda 'reshape') putem să verificăm din nou shape-ul pe care îl are acel array.

In [16]:
arr.shape

(10,)

In [17]:
arr.reshape(2, 5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [18]:
reshaped_arr = arr.reshape(2, 5)
reshaped_arr.shape

(2, 5)

Putem să facem reshape doar dacă numărul de elemente permite să se creeze un nou array pentru noul shape. De exemplu un array de 10 elemente poate să i se facă reshape într-un array cu 2 rânduri și 5 coloane (reshape(2, 5)), dar nu putem să îi facem reshape la un array de 3 rânduri și 5 coloane deoarece în total ar însemna să aibă 15 elemente, dar array-ul nostru are doar 10. Dacă facem asta atunci NumPy ne returnează o eroare prin care ne specifică asta.

In [19]:
arr.reshape(3, 5)

ValueError: cannot reshape array of size 10 into shape (3,5)

O parte importantă din array-urile din numpy este partea de indexare prin care putem să extragem doar anumite valori dintr-un array. Pentru asta o să ne creem o matrice dintr-un array, O să creem un array de 100 de elemente utilizând metoda np.arange() iar după o să îi facem un reshape la acest array prin care să ne creem un array de 10 rânduri și 10 coloane.

In [20]:
matrix = np.arange(0, 100).reshape(10, 10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Cu partea de indexare putem să preluăm anumite valori aflate pe un anumit rând și pe o anumită coloană. O să luăm exemplul în care o să vrem să preluăm elementul aflat pe rândul cu index-ul 2 și coloana cu index-ul 4 (adică numărul 24). Pentru început o să ne creem două variabile care o să rețină valorile acelo indici

In [23]:
row = 2
col = 4

Pentru indexare o să folosim paranteze pătrate unde specificăm rândul și coloane de pe care dorim să preluăm acel element. Prima dată se trece rândul, iar după coloana

In [24]:
matrix[row, col]

24

Prin acest fel am reușit să preluăm numărul 24 care se găsește pe rândul cu index-ul 2 și coloana cu index-ul 4. În loc să creem acele variabile putem să trecem direct index-ul pe care dorim să îl accesăm

In [25]:
matrix[4, 6]

46

Ca să alegem mai multe valori de pe un rând sau de pe o coloană, atuci o să utilizăm partea de slicing. Să extragem toate valorile care sunt pe rândul cu index-ul 3. Pentru asta o să specificăm că dorim elementele de index-ul 3 pentru rânduri, iar pentru coloane o să utilizăm slicing, ca și la liste.

In [26]:
matrix[3, :]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

Acel semn : specifică că dorim să afișăm toate valorile, de la primul la ultimul element. Dacă dorim să extragem doar primele 3 valori de pe acel rând o să mergem doar până la index-ul 3 (care nu este inclus)

In [27]:
matrix[3, :3]

array([30, 31, 32])

Prin acest mod se procedează și atuni când dorim să extragem un număr de elemente dintr-o anumită coloană. Sau dacă dorim să extragem un număr de rânduri de pe un număr de coloane

In [29]:
matrix[:, 2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [30]:
matrix[:5, 2]

array([ 2, 12, 22, 32, 42])

In [31]:
matrix[3:, 5]

array([35, 45, 55, 65, 75, 85, 95])

In [32]:
matrix[2:5, 4:7]

array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])

Acest tip de slicing o să îl folosim în situația în care dorim să modificăm valoarea mai multor elemente din array în același timp. De exemplu, pentru bucata din matrice pe care am preluat-o mai sus (matrix[2:5, 4:7]), acestei bucăți putem să îi atribuim o valoare, iar fiecare element din acea bucată o să aibă nou valoare

In [33]:
matrix[2:5, 4:7] = 0

Dacă vizualizăm acuma matricea o să vedem că o secțiune din aceasta o să aibă valoarea 0, această secțiune este reprezentată de acea secțiune extrasă utilizând slicing.

In [34]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  0,  0, 27, 28, 29],
       [30, 31, 32, 33,  0,  0,  0, 37, 38, 39],
       [40, 41, 42, 43,  0,  0,  0, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Dacă dorim să facem ceva experimente cu anumite valori și nu am vrea să modificăm valoarea matricei originale, atunci putem să creem o copie a aceste matrice. Pentru asta o să ne folosim de metoda .copy() pe care o apelăm asupra matricei pentru care dorim să facem o copie.

In [35]:
matrix_copy = matrix.copy()

In [36]:
matrix_copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23,  0,  0,  0, 27, 28, 29],
       [30, 31, 32, 33,  0,  0,  0, 37, 38, 39],
       [40, 41, 42, 43,  0,  0,  0, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## Recapitulare

În cadrul acestui tutorial am învățat următoarele:

    1.  Cum să creem un numpy.ndarray dintr-o listă din Python

        import numpy as np

        my_list = [1, 2, 3]

        arr = np.array(my_list)

    2.  Cum să creem un array multidimensional (folosind doar valori de zero)

        np.zeros(shape=(2,5))

        # Codul de mai sus creează un array de 2 rânduri și 5 coloane

    3. Cum să creem un array de elemente cu valori random

        np.random.randint(0, 100, 10)

        # Codul de mai sus creează un array de 10 elemente cu valori alese la întâmplare între 0 și 100

    4. Cum să setăm un seed pentru algoritmul de random

        np.random.seed(101)

        np.random.randint(0, 100, 10)

    5. Array-urile au anumite metode aritmetice pe care le putem apela

        arr = np.random.randint(, 100,10)

        arr.nax()  # returnează valoarea cea mai mare din array

        arr.argmax()  # returnează index-ul pe care se găsește valoarea cea mai mare

        arr.min()  # returnează valoarea cea mai mică din array

        arr.argmin()  # returnează index-ul pe care se găsește valoarea cea mai mică

        arr.sum()  # retunrează suma valorilor din array

        arr.mean()  # returnează media valorilor din array

    6. Putem să facem reshape la un array

        arr.reshape(5, 2)

            # Un array de 10 elemente i-am făcut reshape la un array care are tot 10 elemente, dar structurat pe 5 rânduri și două coloane

    7. Cum putem  să preluăm anumite valori dintr-un array utilizând indexare și slicing

        matrix = np.arange(0, 100).reshape(10, 10)

        matrix[row, col] # preluăm valoarea de pe rândul de pe index-ul care este stocat în variabila 'row' și de pe coloana cu index-ul care este stocat în variabila 'col'

        matrix[2, 3] # preluăm elementul aflat pe rândul cu index-ul 2 și coloana cu index-ul 3

        matrix[3, :] # preluăm toate elementele de pe rândul cu index-ul 3, iar prin slicing spunem că dorim să preluăm toate coloanele

        matrix[:, 3] # toate elementele de pe toate rândurile care se găsesc pe coloana cu index-ul 3

        matrix[1:5, 3:9] # slicing atât la rânduri cât și la coloane

    8. Partea de slicing o putem folosi pentru a face o reatribuire la valorile pe care le-am preluat

        matrix[1:5, 3:9] = 0  # la toate valorile cuprinse în acea matrice preluată o să le atribuim valoarea 0

    9. Cum să facem o copie după un array

        copy_matrix = matrix.copy()